package models

import "time"

type CallHistory struct {
	ID                string        `json:"id"`
	CallHistoryUUID   string        `json:"call_history_uuid"`
	CallID            string        `json:"call_id"`
	ConnectType       string        `json:"connect_type"`
	CallType          string        `json:"call_type"`
	Direction         string        `json:"direction"`
	International     bool          `json:"international"`
	HideCallerID      bool          `json:"hide_caller_id"`
	EndToEnd          bool          `json:"end_to_end"`
	CallerExtID       string        `json:"caller_ext_id"`
	CallerName        string        `json:"caller_name"`
	CallerDidNumber   string        `json:"caller_did_number"`
	CallerExtNumber   string        `json:"caller_ext_number"`
	CallerEmail       string        `json:"caller_email"`
	CallerExtType     string        `json:"caller_ext_type"`
	CalleeExtID       string        `json:"callee_ext_id"`
	CalleeName        string        `json:"callee_name"`
	CalleeEmail       string        `json:"callee_email"`
	CalleeDidNumber   string        `json:"callee_did_number"`
	CalleeExtNumber   string        `json:"callee_ext_number"`
	CalleeExtType     string        `json:"callee_ext_type"`
	Department        string        `json:"department"`
	CostCenter        string        `json:"cost_center"`
	SiteID            string        `json:"site_id"`
	GroupID           string        `json:"group_id"`
	SiteName          string        `json:"site_name"`
	StartTime         time.Time     `json:"start_time"`
	AnswerTime        time.Time     `json:"answer_time"`
	EndTime           time.Time     `json:"end_time"`
	CallPath          []CallPath    `json:"call_path"`
	CallerAccountCode string        `json:"caller_account_code"`
	CalleeAccountCode string        `json:"callee_account_code"`
	CallElements      []CallElement `json:"call_elements"`
}

type CallPath struct {
	ID                   string    `json:"id"`
	CallID               string    `json:"call_id"`
	ConnectType          string    `json:"connect_type"`
	CallType             string    `json:"call_type"`
	Direction            string    `json:"direction"`
	HideCallerID         bool      `json:"hide_caller_id"`
	EndToEnd             bool      `json:"end_to_end"`
	CallerExtID          string    `json:"caller_ext_id"`
	CallerName           string    `json:"caller_name"`
	CallerEmail          string    `json:"caller_email"`
	CallerDidNumber      string    `json:"caller_did_number"`
	CallerExtNumber      string    `json:"caller_ext_number"`
	CallerExtType        string    `json:"caller_ext_type"`
	CallerNumberType     string    `json:"caller_number_type"`
	CallerDeviceType     string    `json:"caller_device_type"`
	CallerCountryIsoCode string    `json:"caller_country_iso_code"`
	CallerCountryCode    string    `json:"caller_country_code"`
	CalleeExtID          string    `json:"callee_ext_id"`
	CalleeName           string    `json:"callee_name"`
	CalleeDidNumber      string    `json:"callee_did_number"`
	CalleeExtNumber      string    `json:"callee_ext_number"`
	CalleeEmail          string    `json:"callee_email"`
	CalleeExtType        string    `json:"callee_ext_type"`
	CalleeNumberType     string    `json:"callee_number_type"`
	CalleeDeviceType     string    `json:"callee_device_type"`
	CalleeCountryIsoCode string    `json:"callee_country_iso_code"`
	CalleeCountryCode    string    `json:"callee_country_code"`
	ClientCode           string    `json:"client_code"`
	Department           string    `json:"department"`
	CostCenter           string    `json:"cost_center"`
	SiteID               string    `json:"site_id"`
	GroupID              string    `json:"group_id"`
	SiteName             string    `json:"site_name"`
	StartTime            time.Time `json:"start_time"`
	AnswerTime           time.Time `json:"answer_time"`
	EndTime              time.Time `json:"end_time"`
	Event                string    `json:"event"`
	Result               string    `json:"result"`
	ResultReason         string    `json:"result_reason"`
	DevicePrivateIP      string    `json:"device_private_ip"`
	DevicePublicIP       string    `json:"device_public_ip"`
	OperatorExtNumber    string    `json:"operator_ext_number"`
	OperatorExtID        string    `json:"operator_ext_id"`
	OperatorExtType      string    `json:"operator_ext_type"`
	OperatorName         string    `json:"operator_name"`
	PressKey             string    `json:"press_key"`
	Segment              int       `json:"segment"`
	Node                 int       `json:"node"`
	IsNode               int       `json:"is_node"`
	RecordingID          string    `json:"recording_id"`
	RecordingType        string    `json:"recording_type"`
	HoldTime             int       `json:"hold_time"`
	WaitingTime          int       `json:"waiting_time"`
	VoicemailID          string    `json:"voicemail_id"`
}

type CallElement struct {
	CallElementID        string    `json:"call_element_id"`
	CallID               string    `json:"call_id"`
	ConnectType          string    `json:"connect_type"`
	CallType             string    `json:"call_type"`
	Direction            string    `json:"direction"`
	HideCallerID         bool      `json:"hide_caller_id"`
	EndToEnd             bool      `json:"end_to_end"`
	CallerExtID          string    `json:"caller_ext_id"`
	CallerName           string    `json:"caller_name"`
	CallerEmail          string    `json:"caller_email"`
	CallerDidNumber      string    `json:"caller_did_number"`
	CallerExtNumber      string    `json:"caller_ext_number"`
	CallerExtType        string    `json:"caller_ext_type"`
	CallerNumberType     string    `json:"caller_number_type"`
	CallerDeviceType     string    `json:"caller_device_type"`
	CallerCountryIsoCode string    `json:"caller_country_iso_code"`
	CallerCountryCode    string    `json:"caller_country_code"`
	CalleeExtID          string    `json:"callee_ext_id"`
	CalleeName           string    `json:"callee_name"`
	CalleeDidNumber      string    `json:"callee_did_number"`
	CalleeExtNumber      string    `json:"callee_ext_number"`
	CalleeEmail          string    `json:"callee_email"`
	CalleeExtType        string    `json:"callee_ext_type"`
	CalleeNumberType     string    `json:"callee_number_type"`
	CalleeDeviceType     string    `json:"callee_device_type"`
	CalleeCountryIsoCode string    `json:"callee_country_iso_code"`
	CalleeCountryCode    string    `json:"callee_country_code"`
	ClientCode           string    `json:"client_code"`
	Department           string    `json:"department"`
	CostCenter           string    `json:"cost_center"`
	SiteID               string    `json:"site_id"`
	GroupID              string    `json:"group_id"`
	SiteName             string    `json:"site_name"`
	StartTime            time.Time `json:"start_time"`
	AnswerTime           time.Time `json:"answer_time"`
	EndTime              time.Time `json:"end_time"`
	Event                string    `json:"event"`
	Result               string    `json:"result"`
	ResultReason         string    `json:"result_reason"`
	DevicePrivateIP      string    `json:"device_private_ip"`
	DevicePublicIP       string    `json:"device_public_ip"`
	OperatorExtNumber    string    `json:"operator_ext_number"`
	OperatorExtID        string    `json:"operator_ext_id"`
	OperatorExtType      string    `json:"operator_ext_type"`
	OperatorName         string    `json:"operator_name"`
	PressKey             string    `json:"press_key"`
	Segment              int       `json:"segment"`
	Node                 int       `json:"node"`
	IsNode               int       `json:"is_node"`
	RecordingID          string    `json:"recording_id"`
	RecordingType        string    `json:"recording_type"`
	HoldTime             int       `json:"hold_time"`
	WaitingTime          int       `json:"waiting_time"`
	VoicemailID          string    `json:"voicemail_id"`
}
